sudo: required

language: c

services:
  - docker

before_install:
  - docker build -t jena-fuseki jena-fuseki

script:
# Run RDF database in order to save tests and results
  -   docker run --privileged --name instance.tft_database -d jena-fuseki

# Run extern servers for tests
  -   docker run --privileged --name  instance.tft.example.org -h example.org -d  jena-fuseki
  -   docker run --privileged --name  instance.tft.example1.org -h example1.org -d  jena-fuseki
  -   docker run --privileged --name  instance.tft.example2.org -h example2.org -d  jena-fuseki
  -   docker run --privileged --name instance.jena-fuseki -h jena-fuseki -d jena-fuseki
  -   docker inspect bridge
