notifications:
  email:
      - karima.rafes@gmail.com

sudo: required

language: php
php:
  - '7.1'

services:
  - docker

before_install:
  - docker pull bordercloud/tft-virtuoso7-stable
  - docker build -t tft-jena-fuseki .

script:
# Deploy TFT
# Run RDF database in order to save tests and results
  -   docker run --privileged --name instance.tft_database -d tft-jena-fuseki
  -   docker run --privileged --name instance.tft.example.org -h example.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d bordercloud/tft-virtuoso7-stable
  -   docker run --privileged --name instance.jena-fuseki -h tft-jena-fuseki -d tft-jena-fuseki
  -   git clone --recursive https://github.com/BorderCloud/TFT.git
  -   cd TFT
  -   composer install --dev
  -   ls
  -   php ./tft-testsuite -a -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update
  -   php ./tft -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -tt fuseki -tq http://172.17.0.6/test/query -tu http://172.17.0.6/test/update -r https://github.com/BorderCloud/tft-jena-fuseki/$TRAVIS_BUILD_ID -o ./junit --softwareName="Jena Fuseki"  --softwareDescribeTag=v3.4.0
  -   php ./tft-score -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -r  https://github.com/BorderCloud/tft-jena-fuseki/$TRAVIS_BUILD_ID

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
    docker push bordercloud/tft-jena-fuseki;
    fi
