sudo: required

language: php
php:
  - '7.1'

services:
  - docker

#before_install:
#  - docker build -t tft_virtuoso7_stable_service services
#  - docker build -t jena-fuseki jena-fuseki

script:
# Deploy TFT
# Run RDF database in order to save tests and results
#  -   docker run --privileged --name instance.tft_database -d jena-fuseki
#  -   docker run --privileged --name instance.tft.example.org -h example.org -d tft_virtuoso7_stable_service
#  -   docker run --privileged --name instance.tft.example1.org -h example1.org -d tft_virtuoso7_stable_service
#  -   docker run --privileged --name instance.tft.example2.org -h example2.org -d tft_virtuoso7_stable_service
#  -   docker run --privileged --name instance.jena-fuseki -h jena-fuseki -d jena-fuseki
  -   git clone --recursive https://github.com/BorderCloud/TFT.git
  -   ls
  -   ./TFT/tft-testsuite -a -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -d
  -   ./TFT/tft -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -tt fuseki -tq http://172.17.0.7/test/query -tu http://172.17.0.7/test/update -r https://github.com/BorderCloud/TFT/jena-fuseki/v3.4.0 -o ./junit --softwareName="Jena Fuseki"  --softwareDescribeTag=v3.4.0 -d
  -   ./TFT/tft-score -t fuseki -q http://172.17.0.2/test/query -u http://172.17.0.2/test/update -r  https://github.com/BorderCloud/TFT/jena-fuseki/v3.4.0  -d

